name: pr checker

on:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]

jobs:
  test:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace